### PR TITLE
Design Report: Abstract and Description A+B

### LINKED ISSUE #58: [DOCS] - Design Report Section: Description
Adapt from #52.

  - [ ] What the technology is, what it does, how it functions, and how the crew will interact with it
  - [ ] Descriptions of major hardware components and processes, subsystems
  - [ ] Basic operations concept of the food production technology, assumptions and operational prereqs/requirements

### LINKED ISSUE #60: [DOCS] - Design Report Section: Design Abstract
"What is your proposed solution? What is novel, sustainable, and innovative about your proposed solution? What types of food does your solution create? How are you minimizing inputs and maximizing food outputs?", see [Pitch](https://docs.google.com/document/d/1bnGLgyWJCuQOkYLvpEQFeSjZWFdelap_4pfn6VQ7juw/edit?usp=sharing), Animation Script

### PR DESCRIPTION
**Pull request by JLefebvre55**
Closes #58, #60

### CODE REVIEW

**Comment by JLefebvre55** [comment]
Revisions:
- [ ] Abstract should be less features, more approach/concept/scope and justification (novel, sustainable, innovative)
- [ ] Reduce system description detail in A - remember, this is a design concept submission
- [ ] Mention assumed life support etc. systems - A or B?

**Review by nchareunsouk — COMMENTED** [review]
revisions noted

**Review by narvcharv — CHANGES_REQUESTED** [review]
Abstract:

- Excellent overview of the entire design
- [x] Change some language to connect approach to justification (i.e. "while collecting data on plant growth and improving yields over time" could be "while collecting data on plant growth in order to improve yields over time"
- [x] "Both plant support trays and lighting systems..." might be interpreted as "The two plant support trays and lighting systems..." to a first-time reader
- [x] Last line feels disconnected, could use something like: "By combining all of these features into a sleek package, PeaPod provides..."



Part A:

- [x] "some feedback-based" --> "some of which are feedback-based"
- [x] Define PID before using the acronym
- ~~Use "Venturi Tube" before using Venturis~~
- [x] "w/" --> "with"


Part B:

- No comments other than what's at the end of my Part A comments, I think this is well written and hits the prompt.

**Comment by JLefebvre55** [comment]
> Use "Venturi Tube" before using Venturis

@narvcharv venturi as a noun is actually a common thing, they use it like that in both automotive and gardening stuff

**Review by narvcharv — APPROVED** [review]
lookin' clean 😎

**Pull request merged**
