### PR TITLE
Fixed #76

### LINKED ISSUE #76: [FEATURE] - Design Report: Crew Time Performance Constraint (2.3.6/2.3.9)
**Add manual pollination as a potential crew time requirement.**
Most vegetables (roots) such as potatoes and carrots may not require pollination but fruits such as strawberries do. 
Also, some plants like cucumbers are self-pollinating.
Manual pollination would most likely require swabbing each plant (only during the pollination period).

_Note: Periodic turbo blower fans may be a way to automate pollination._

**Output processing**
Provide 2-3 examples of different kinds of output processing with time requirements

**Output storage**
There are refrigerators on the ISS

### PR DESCRIPTION
**Pull request by narvcharv**
Briefly introduce the scope of the changes included in this pull request.

- Added time consideration for manual pollination
- Closes #76

### Checklist
Put an `X` in the boxes that apply. I have:
- [X] Referenced related issues;
- [X] Added proper scope and status labels (i.e. *Scope: Review Needed*);
- [X] Mentioned related review teams (i.e. @utagritech/admins);

### CODE REVIEW

**Comment by JLefebvre55** [comment]
@narvcharv did you see the other two tasks in #76 ?

**Review by JLefebvre55 — CHANGES_REQUESTED** [review]
re: comment

**Comment by narvcharv** [comment]
fixed, pls ping if you want more i'd be happy to :)

**Review by JLefebvre55 — APPROVED** [review]
Post Malone

**Pull request merged**
