### PR TITLE
Design Report Section: Constraints

### LINKED ISSUE #53: [DOCS] - Design Report Section: Adherence to Constraints
> To be developed on a branch named `docs-designreport-constraints`

Show consideration and details; Include the following (_300 chars each_):
  - [x] Volume/Dimensions - @JonasMarshall 
  - [x] Power - @JLefebvre55 
  - [x] Water - @JLefebvre55 
  - [x] Mass - @JonasMarshall
  - [x] Data Connection - @JLefebvre55  
  - [x] Crew Time - @narvcharv 
  - [x] Operational Constraints - @narvcharv 
  - [x] Extra? constraints Requirements doc inheriting from `[2]`, as well as R1d, R4, R5? - @narvcharv

### PR DESCRIPTION
**Pull request by JLefebvre55**
Closes #53.

### CODE REVIEW

**Review by nchareunsouk — CHANGES_REQUESTED** [review]
Minor Revision
- [x] @narvcharv Update 2.3.6 Crew Time Requirement to reflect changes in nutrient and pH solution handling procedure outlined in [`/docs/design/solutionoverview`](https://github.com/UTAgritech/PeaPod/tree/docs-solutionoverview/docs/design/solutionoverview) (nutrients and pH sections). (An inline system is going to be used instead of the syringes so the solution reservoirs only need to to be refilled.)

Looking good 👍

**Review by nchareunsouk — DISMISSED** [review]
Minor addition:
@JLefebvre55 A second footnote could be added under 2.3.2 Power Consumption to clarify that the calculated max consumption is for one "unit" but that each unit can be expanded as long as they share the same environment.

**Comment by JLefebvre55** [comment]
@nchareunsouk @narvcharv are 2.3.5 and 2.3.10 the same?? If so can we merge them?

**Comment by nchareunsouk** [comment]
> are 2.3.5 and 2.3.10 the same?? If so can we merge them?

@JLefebvre55 I think they're similar enough to merge but there could be a benefit to leaving them separate if there's a 300 char limit per constraint. Having them separate would potentially allow for more detail about the computer vision and connectivity infrastructure.

**Comment by JLefebvre55** [comment]
> I think they're similar enough to merge but there could be a benefit to leaving them separate if there's a 300 char limit per constraint.

@nchareunsouk I mean, are they filling in the same "data connection" constraint?

**Comment by JLefebvre55** [comment]
I'm merging them.

**Review by nchareunsouk — APPROVED** [review]
👍

**Pull request merged**
