### PR TITLE
Solution Overview Draft

### LINKED ISSUE #52: [FEATURE] - Solution Overview Draft
> Assigned to @JLefebvre55, @nchareunsouk, due by **July 3rd**

### **NOTE**: PR has been linked. Work is to be done on the `docs-solutionoverview` branch.

**Here**: [`/docs/design/solutionoverview`](https://github.com/UTAgritech/PeaPod/tree/docs-solutionoverview/docs/design/solutionoverview)

**Scope**: Detail the **purpose**, **function** (inputs/outputs, system vs. surroundings, assumptions), and **method** (process steps/tree) of the system. If the method is multi-step (aka relies on a multi-part system), recurse (**features**) and inherit.
- [x] Detail _overall_ solution
- [x] Detail subsystems:
  - [x] Automation - @JLefebvre55 
  - [x] Housing - @JLefebvre55 
  - [x] Aeroponics - @nchareunsouk 
  - [x] Environment Control
    - [x] Air Temperature - @nchareunsouk 
    - [x] Air Humidification - @JLefebvre55 
    - [x] Air Dehumidification - @nchareunsouk 
    - [x] Solution Temperature - ~~@nchareunsouk~~ @JLefebvre55 
    - [x] Solution Nutrients - @nchareunsouk 
    - [x] Solution pH - @nchareunsouk 
    - [x] Lighting - @JLefebvre55 
  - [x] Optimization - @JLefebvre55

### PR DESCRIPTION
**Pull request by JLefebvre55**
Closes #52. Also refactored naming to "solution overview".

### CODE REVIEW

**Review by narvcharv — DISMISSED** [review]
lookin' good 😎

**Comment by JLefebvre55** [comment]
@narvcharv OOP this is still a draft lmfao, don't need review yet. Thanks tho 👍

**Comment by JLefebvre55** [comment]
@narvcharv Check it out

**Comment by JLefebvre55** [comment]
@nchareunsouk added you as a reviewer, mark for completeness/thoroughness/detail as well as the usual formatting/grammar

**Review by nchareunsouk — DISMISSED** [review]
awesome 👍

**Review by narvcharv — CHANGES_REQUESTED** [review]
- [x] 2: "The primary _functions_ of the overall design
- [x] 2.1: Second bullet point of Justification has a typo "...topology is common is well suited..."
- [x] 2.2: Features-->Grow trays "...(See 2.3), and misting container."
- [x] 2.2: Justification-->Features could use another word in the first line "Aluminum extrusion is commonly used for frames because... [it is strong yet lightweight]"
- [x] 2.3: Justification-->Method last sentence to "Mean droplet size of 5-50 micron is optimal to plant growth."
- [x] 2.3.1: Justification-->Features last sentence to "Built-in level sensors allow for notifications to refill."
- [x] 2.4.3: Method - specify how air is circulated through the dehumidifier (it is mentioned later in Features, but I think it would be helpful in Method as well)
- [x] 2.4.3: Features - "Evaporator Oven" sounds, to an outside ear, like a massive investment in both size and cost, so maybe add a footnote specifying what those are
- [x] 2.5: "Aka" sticks out compared to the formality of the rest of the section

Looks _incredible_, just these small changes ^

**Comment by JLefebvre55** [comment]
> * [ ]  General: Hyperlink references?

What specifically? Like sources for claims?

**Comment by narvcharv** [comment]
Disregard that point---I added that when I saw the the citation [1] (assuming there would be more) but then realized that's the only citation, so I don't think it's necessary.

**Comment by JLefebvre55** [comment]
@narvcharv Done!

@nchareunsouk it re-requests your review by default

**Review by nchareunsouk — APPROVED** [review]
👍

**Review by narvcharv — APPROVED** [review]
lookin' good 😎

**Pull request merged**
